name: CI/CD Java Maven

on:
  push:
    branches:
      - 'feature/**'
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build with Success
        env:
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          echo $REPO_NAME:$(date +%s)
          echo "${GITHUB_ENV}"
          echo "REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}"
          echo "REPOSITORY: ${REPOSITORY}"
          echo "USUARIO: ${USERNAME}"
          echo "Build realizado com sucesso"